# Generated by Django 5.0.6 on 2024-05-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('working_days', models.CharField(choices=[('SEG-SEX', ' Segunda à Sexta das 09h as 18h'), ('SAB-DOM', 'Sabado à Domingo')], max_length=200)),
                ('hours', models.CharField(choices=[('09h-18h', '09h as 18h'), ('11h-20h', '11h as 20h')], max_length=100)),
            ],
        ),
    ]
