# Generated by Django 5.0.6 on 2024-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='working_days',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('DOCES', 'Doces'), ('SAlGADOS', 'Salgados'), ('SUCOS', 'Sucos'), ('REFRIGERANTES', 'Regrigerantes'), ('MASSAS', 'Massas'), ('Vegetariano', 'Vegetariano')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
