# Generated by Django 5.0.6 on 2024-05-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='photo',
        ),
    ]
