# Generated by Django 5.0.6 on 2024-05-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_restaurant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='products',
        ),
    ]
